### ISSUE TITLE
Suggestion To Improve User Friendliness.

### ISSUE THREAD

**Issue by HNik500** [o-david/EasyGit-CLI#1]
Hello Mr. David i had a suggestion which could improve your work. When using the config, i would suggest that the terminal would ask you to confirm your name and e-mail, it would also give the user the flexibility to allow them to changed their name and password.

**Comment by o-david** [comment]
Thanks for the feedback, I'll add that right away

**Comment by o-david** [comment]
Done, thanks again for your feedback.
