### ISSUE TITLE
 Customizable Aliases for Enhanced User Experience

### ISSUE THREAD

**Issue by TKkosi** [o-david/EasyGit-CLI#3]
I would like to propose the addition of customizable aliases in the Easy Git project. This feature will allow users to define their own shortcuts for commonly used commands, making the tool more personalized and user-friendly.
 For example, users could set fp as an alias for first push, co as an alias for checkout.

I believe that Implementing customizable aliases will significantly enhance the user experience of Easy Git by allowing users to streamline their workflows with personalized shortcuts. This feature aligns with the goal of making Git operations as intuitive and efficient as possible.

Benefits.
- Personalization : Users can tailor the command line interface to their preferences, improving their workflow and efficiency.
- Ease of Use :  Shorter commands reduce typing effort and minimize the risk of errors.
- Consistency : Users coming from other Git tools or workflows can set up aliases that match their existing habits.

**Comment by o-david** [comment]
@TKkosi I have implemented this and am getting great user feedback. Thank you very much for your contribution to this project
<img width="750" alt="Screenshot 2024-06-18 at 12 35 32" src="https://github.com/o-david/EasyGit-CLI/assets/30634148/aec44118-8fcb-4741-91fd-0911f412dc07">
