### ISSUE TITLE
Problem with easygit add-alias [alias] [command] Command

### ISSUE THREAD

**Issue by TKkosi** [o-david/EasyGit-CLI#4]
## Steps to Reproduce:

Run the command easygit add-alias [alias] [command] in the terminal.

### Expected behavior: 
Alias [alias] should be added for the command [command].

###Actual behavior: 
Error message "input not found" is displayed.

## Additional Details:

If the command easygit add-alias is run without specifying [alias] and [command], it prompts for these inputs and successfully adds the alias.

### Screenshots or Logs:
![easygitBug](https://github.com/o-david/EasyGit-CLI/assets/169730450/65052f4a-3565-4f66-9d07-148878860d9a)

### Notes:

This issue occurs consistently when attempting to use the [alias] [command] syntax as described in the documentation. Please advise on the correct usage or address the issue with the command handling.

**Comment by o-david** [comment]
Thanks, will check it out right away

**Comment by o-david** [comment]
Fixed thanks again for sharing
